title: Zhenyu Guan's Homepage
page-top-title: Zhenyu Guan
top-section-bg-text: Be what you wanna be
home-subtitle: Zhenyu Guan&ensp;|&ensp;管振宇
copyright-text: '&copy; Zhenyu Guan 2023-2025. All Rights Reserved.'
